services:

  db:
    image: postgres:latest
    container_name: pokedex_database
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: pokedex-data
    ports:
      - "5432:5432"
    volumes:
      - ./backend:/app/backend
      - ./backend/postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: pokedex_backend
    container_name: pokedex_backend
    env_file:
      - .env
    ports:
      - '${BACKEND_PORT}'
    volumes:
      - ./backend:/app/backend # Mount backend source code
      - ./shared:/app/shared # Mount shared source code
      - /app/backend/node_modules:delegated
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: pokedex_frontend
    container_name: pokedex_frontend
    env_file:
      - .env
    ports:
      - '${FRONTEND_PORT}' # Vite default port
    volumes:
      - ./frontend:/app/frontend # Mount frontend source code
      - /app/frontend/node_modules:delegated


  nginx:
    build: ./nginx
    image: nginx:pokedex
    container_name: nginx_pokedex
    ports:
      - '8446:8446'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/uploads:/app/backend/database/uploads
    depends_on:
      - frontend
      - backend

volumes:
  uploads:
  pnpm_store:
